project:
  type: website
  resources: 
    - CNAME
  output-dir: _site

website:
  title: "Easy Geom Recipes"
  reader-mode: true
  repo-url: https://github.com/EvaMaeRey/easy-geom-recipes
  repo-actions: [edit, issue]
  sidebar:
    contents:
      - section: "Tutorial"
        contents:
          - href: easy_geom_recipes.qmd
          - href: easy_geom_recipes_compute_panel.qmd
          - href: easy_geom_recipes_compute_group.qmd
      - section: "Focus Group"
        contents:
          - href: invitation_to_participate.qmd
          - href: focus_group_results_summary.qmd
          - href: focus_group_script.qmd
      - section: "Survey"
        contents:
          - href: survey_results_summary.qmd
          - href: survey_instrument.qmd
format: 
  html:
    toc: true

filters:
 - webr