project:
  type: website
  resources:
    - CNAME
  output-dir: _site

website:
  announcement:
    icon: info-circle
    dismissable: true
    content: "Easy geom_*() recipes is open for comment. Please feel free to be in touch about issues (report an issue/edit this page/email/[discuss](https://github.com/EvaMaeRey/easy-geom-recipes/discussions)). Recipe #1 is close to final form, and I will use that as a model - incorporating your feedback."
    type: primary
    position: below-navbar
  title: "Easy geom_*() recipes 🫖"
  reader-mode: true
  repo-url: https://github.com/EvaMaeRey/easy-geom-recipes
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial-preview.qmd
        text: Tutorials
      # - href: research.qmd
      #   text: Research
    right:
      - icon: github
        href: https://github.com/evamaerey/easy-geom-recipes
  sidebar:
    contents:
      - section: "Tutorials"
        contents:
          - href: preview.qmd
          - href: recipe1means.qmd
          - href: recipe2coordinates.qmd
          - href: recipe3balance.qmd
          - href: recipe4catlm.qmd


      # - section: "Tutorial Evaluation"
      #   contents:
      #     - href: survey_results_summary.qmd
      #     - href: focus_group_script.qmd
      #     - href: focus_group_highlights.qmd
      #     - href: invitation_to_participate.qmd
      #     - href: survey_instrument.qmd
      #     - href: 2023_easy_geom_recipes.qmd

format:
  html:
    theme: theme.scss
    toc: true

filters:
 - webr


