---
title: "Easy geom recipes"
author: Gina Reynolds
---

Extending ggplot2 is a powerful way to enhance productivity and make coding plots more enjoyable. The ggplot2 extension system allows us to build new 'vocabulary' for more fluent expression.

Yet some useful areas of extension not in mainstream use, even among seasoned ggplot2 users.

*Easy geom recipes* is a new point of entry for learning ggplot2 *Stat* extension, a particularly powerful mechanism which allows users to define computation to be used in new geom\_\*() or stat\_\*() functions.

With new Stats, *you* can specify calculation to be done within the ggplot2 plot pipeline:

```{r}
#| eval = F
ggplot(data = cars,
       aes(x = speed, y = dist)) + 
  geom_customized()  # YOU specify compute
```

In this project's tutorials, you'll see how to define Stats your own stats and write new user-facing geom\_\*() or stat\_\*() functions.

The materials are aimed at academics, data analysts, BI professionals, seasoned and new ggplot2 users, statistics educators and their students, journalists, etc. The approach has been tested and evaluated by data science and statistics educators.

# Where to next:

[**Let's get cooking!**: *Work through Intro Recipes 1-3: compute_group*](\easy_geom_recipes_compute_group.html){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Take me to lesson 1."}

[**Taste without cooking?**: *Leaf through some recipes*](https://evamaerey.github.io/mytidytuesday/2022-01-03-easy-geom-recipes/easy_geom_recipes_flipbook_2024.html){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Take me to lesson 1."}

[**Tested and evaluated?**: *Why use the recipes*](\research.html){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Research on the new approach"}

[**'My problem's not that easy.'** *I want even more recipe-like examples*](easy_geom_recipes_compute_group.qmd){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Take me to lesson 1."}

[**What if I get stuck.** *Is there a support group?*](https://github.com/teunbrand/ggplot-extension-club/discussions){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Take me to lesson 1."}

[**Why so hungry?** *What's motivating all this*](https://evamaerey.github.io/everyday_ggplot2_extension/){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Take me to lesson 1."}

