---
title: "Invitation to Participate"
author: "Evangeline Reynolds"
date: "4/21/2023"
output: html_document
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```

Dear ____,

I’m reaching out to you because I consider you to be a ggplot2 super-user and educator.

I would like to have your feedback about a ggplot2 extension tutorial: ‘Easy Geom Recipes’.  I hope to use this recipes model for future tutorials as well, so getting your feedback on this first tutorial will be very valuable.

Would you be willing to review and complete the geom tutorial below?  It walks through three examples of geom extensions and then prompts to build a variant.

> The tutorial worksheet: https://raw.githubusercontent.com/EvaMaeRey/mytidytuesday/master/2022-01-03-easy-geom-recipes/easy_geom_recipes.Rmd  (see a rendered version here: https://evamaerey.github.io/mytidytuesday/2022-01-03-easy-geom-recipes/easy_geom_recipes.html )

> Then, I’d ask that you complete the following survey with your initial feedback and some information about yourself: XXXXXXXXXX

Finally, I’m planning a virtual focus group meeting (under 1hr) on the tutorial and ggplot2 extension experiences.  This session will be recorded for the purposes of retaining feedback via a transcript.  Comments will be deidentified and the video deleted once the transcript is checked and finalized.  Individuals’ comments will not be shared with participants' names or identifiable information.  A poll on date and time preferences will follow.

Thank you for your participation and willingness to provide feedback on the "Easy Geom Recipes" study!  Participation in this study is voluntary and you may withdraw from participation at any time without loss of benefits.

Sincerely,

Evangeline Reynolds
