---
title: "layer fundamentals"
editor: visual
---




```{r}
library(ggplot2) 

ggplot(mpg) + 
  aes(x = hwy, y = cty) + 
  geom_point()

ggplot(mpg) + 
  aes(x = hwy, y = cty) + 
  geom_point(stat = "identity")

ggplot(mpg) + 
  aes(x = hwy, y = cty) + 
  layer(geom = "point",
        stat = "identity",
        position = "identity")

ggplot(mpg) + 
  aes(x = hwy, y = cty) + 
  layer(geom = GeomPoint,
        stat = StatIdentity,
        position = position_identity())

names(StatIdentity)  
  
StatIdentity$compute_layer

data.frame(x = 1, y = 1) |>
  StatIdentity$compute_layer()
```






```{r}
ggplot(diamonds) + 
  aes(x = cut) + 
  geom_bar()

ggplot(diamonds) + 
  aes(x = cut) + 
  layer(geom = "bar",
        stat = "count",
        position = "stack")

ggplot(diamonds) + 
  aes(x = cut) + 
  layer(geom = GeomBar,
        stat = StatCount,
        position = position_stack())


names(StatCount)  

StatCount$compute_group

data.frame(x = c("A", "A", "B")) |> 
  StatCount$compute_group()

library(dplyr)
diamonds |> 
  dplyr::summarize(count = dplyr::n(), .by = cut) |>
  ggplot() + 
  aes(x = cut, y = count) + 
  layer(geom = GeomBar,
        stat = StatIdentity,   # non-computing Stat
        position = position_stack())
```
