---
format: gfm
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Easy geom recipes: a new entry point to plotnine extension 

This tutorial introduces a new introductory tutorial in plotnine extension.
The tutorial explores six layer extensions in a step-by-step fashion.
Three of the extensions are fully-worked examples. After each of the
worked examples, the tutorial prompts the learner to work through a
similar extension.

### Background and motivation

Using grammar of graphics implmentations have been described as writing ‘graphical poems’. But we
may feel at a loss for ‘words’ when functions we’d like to have don’t
exist. The plotnine extension system allows us to build new ‘vocabulary’
for fluent expression.

An exciting extension mechanism is that of inheriting from existing,
more primitive geoms after performing some calculation.

To get feet wet in this world and provide a taste of patterns for geom
extension, ‘easy geom recipes’ provide three basic examples of the
geoms\_ that inherit from *existing* geoms (point, text, segment, etc)
along with a practice exercise:
https://has2k1.github.io/easy-geom-recipes/easy_geom_recipes_compute_group.html.

With such geoms, calculation is done under the hood by the ggplot2
system. We’ll see how to define a ggproto object; The tutorial keeps
things simple by only defining computation at the compute_group and compute_panel stage.

With new geoms, you can write *new* graphical poems with exciting new
graphical ‘words’!

The tutorial is intended for individuals who already have a working
knowledge of the grammar of ggplot2, but may like to build a richer
vocabulary for themselves.

### Motivation

- ggplot2 extension underutilized

- inaccessibility to demographic that might really benefit

- statistical storytelling benefits from greater fluidity that new geoms
  afford

- traditional entry point (themes) might not be compelling to an
  audience that might be really productive in extension!

- repetition and numerous examples useful in pedegogical materials

### Tutorial form

The introductory tutorial took the form of three examples where a
geom\_\* is successfully created in a step-by-step fashion. After each
example, the learner is prompted to create an additional geom that is
computationally similar to the example.

Our recipes take the form:

- Step 0. Get the job done with ‘base’ plotnine. It’s a good idea to
  clarify what needs to happen without getting into the extension
  architecture
- Step 1. Write a computation function. Wrap the necessary computation
  into a function that your target geom\_\*() function will perform. We
  focus on ‘compute_group’ computation only in this tutorial.
- Step 2. Define a ggproto object. ggproto objects allow your extension
  to work together with base plotnine functions! You’ll use the
  computation function from step 1 to help define it.
- Step 3. Write your geom function! You’re ready to write your function.
  You will incorporate the ggproto from step 2 and also define which
  more primitive geom (point, text, segment etc) you want other
  behaviors to inherit from.
- Step 4. Test/Enjoy! Take your new geom for a spin! Check out
  group-wise computation behavior!
