---
title: "Recipe #1, `geom_medians() and geom_means()`"
pyodide:
  packages:
    - plotnine
execute:
  echo: false
  warning: false
---

```{python}
#| label: imports

from plotnine import *
from plotnine.layer import layer
from plotnine.session import last_plot
from plotnine.data import penguins
```

# The Goal

In this first recipe, we'll look at simple examples of defining a new `geom_*()` function, `geom_medians()` and `geom_means()`.  

Each `geom_*()` function (layer) is defined by three major elements: a `Geom`, a `Stat`, and a `position`.  The simplest among these to create is a new `Stat`, so the 'Easy recipes' start with these. And while simple, `Stats` are also powerful because they allow you compute to be integrated into your plotting pipeline --- that you would otherwise might need to do 'manually' before plotting.  

Along with writing the `geom_\*()` function, we'll write a `stat_*()` function, which is pretty typical for seasoned plotnine developers when writing `Stats`. It's okay if *you* don't typically write your plots with `stat_*()` functions -- you can use just use the `geom_*()` functions if you like.

::: {.callout-tip}

# Note that in the plotnine extension context, the word 'layer' *only* refers to `geom_*()`, `stat_*()`, and `annotate()` functions.  These all use the `layer()` function internally -- a function that requires --- you guessed it --- a `Geom`, a `Stat`, and a `position`!

:::

Let's get started!  Our objective in this first 'recipe' is to be able to compose the following plot with a new `geom_means()` function that we will create.


```python
(
    ggplot(data=penguins)
    + aes(x="bill_depth_mm", y="bill_length_mm")
    + geom_point()
    + geom_means(size=8, color="red") # new function!
)
```


```{pyodide}
#| echo: false
#| warning: false
from plotnine import *
from plotnine.data import penguins

penguins_medians = (
    penguins[["bill_length_mm", "bill_depth_mm"]]
    .median()
    .to_frame()
    .T
    .add_suffix("_median")
)

(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point()
  + geom_point(
      penguins_medians,
      aes(x="bill_depth_mm_median", y="bill_length_mm_median"),
      size=8,
      color="red",
   )
)
```

In this exercise, we'll demonstrate how to define the new extension function `geom_medians()` to add a point at the medians `x` and `y`. Then you'll be prompted to define `geom_means()` based on what you've learned.

---


## Step 00: Loading packages and prepping data

<!-- Handling missingness is not a discussion of this tutorial, so we'll only use complete cases. -->

```{python}
from plotnine import *
from plotnine.data import penguins

penguins.head()
```

## Step 0: use base ggplot2 to get the job done


It's a good idea to get things done without Stat extension first, just using 'base' ggplot2. The computational moves you make here can serve a reference for building our extension function.


```{python}
#| label: penguins
penguins_medians = (
    penguins[["bill_length_mm", "bill_depth_mm"]]
    .median()
    .to_frame()
    .T
    .add_suffix("_median")
)

(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point()
  + geom_point(
      penguins_medians,
      aes(x="bill_depth_mm_median", y="bill_length_mm_median"),
      size=8,
      color="red",
   )
  + labs(title="Created with base plotnine")
)
```


::: {.callout-tip collapse="true"}
### Pro tip.  Use `ggplot.layer_data()` to inspect plotnine\'s internal data ...

Use `ggplot.layer_data()` to inspect the render-ready data internal in the plot.  Your Stat will help prep data to look something like this.

```{python}
last_plot().layer_data(i=1) # layer 2, the computed means, is of interest
```
:::


## Step 1: Define compute. Test.

Now you are ready to begin building your extension function. The first step is to define the compute that should be done under-the-hood when your function is used.  We'll define this in a function called `compute_group_medians()`.  The `data` input will look similar to the plot data.  You will also need to include a `scales` argument, which plotnine uses internally.

### Define compute.

```{python}
#| label: compute_group_medians
import pandas as pd

def compute_group_medians(data, scales=None):
    return data[["x", "y"]].median().to_frame().T
```

::: {.callout-note collapse="false"}
# You may have noticed ... 

1. **... that the compute function can only be used with data with variables `x` and `y`.**  These aesthetic variables names, relevant for building the plot, are generally not found in the raw data inputs for plot.
:::


### Test compute.

```{python}
# Test compute. 
(
    penguins
    .eval("x = bill_depth_mm")
    .eval("y = bill_length_mm")
    [["x", "y"]]
    .pipe(compute_group_medians)
)
```

::: {.callout-note collapse="false"}
# You may have noticed ... 

**... that we prepare the data to have columns with names `x` and `y` before testing.**  Computation will fail if variables `x` and `y` are not present given the function's definition.  In a plotting setting, columns are renamed by mapping aesthetics, e.g. `aes(x="bill_depth", y="bill_length")`.
:::


## Step 2: Define new Stat. Test.

Next, we use the ggplot2::ggproto function which allows you to define a new Stat object - which will let us do computation under the hood while building our plot. 

<!-- https://ggplot2.tidyverse.org/reference/ggproto.html -->

### Define Stat.


```{python}
#| label: stat_medians

from plotnine.stats.stat import stat

class stat_medians(stat):
    REQUIRED_AES = {"x", "y"}
    DEFAULT_PARAMS = {"geom": "point"}

    def compute_group(self, data, scales):
        return compute_group_medians(data)
```

<!-- TODO: Revise -->
::: {.callout-note collapse="false"}
# You may have noticed... 

1. **... that the naming convention for the `ggproto` object is written in  CamelCase. **The new class should also be named the same, i.e. `"StatMedians"`.
2. **... that we inherit from the 'Stat' class.**  In fact, your ggproto object is a *subclass* -- you are inheriting class properties from ggplot2::Stat. 

3. **... that the `compute_group_medians` function is used to define our Stat's `compute_group` element.** This means that data will be transformed group-wise by our compute definition -- i.e. by categories if a categorical variable is mapped.

4. **... that setting `required_aes` to `x` and `y` reflects the compute functions requirements** Specifying `required_aes` in your Stat can improve your user interface. Standard ggplot2 error messages will issue if required aes are not specified, e.g. "`stat_medians()` requires the following missing aesthetics: `x`."
  


<!-- https://yjunechoe.github.io/posts/2022-07-06-ggplot2-delayed-aes-2/#ggproto-minus-the-gg-and-the-proto  -->

:::


### Test Stat.

You can test out your Stat using them in ggplot2 `geom_*()` functions.  

```{python}
(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point()
  + geom_point(stat=stat_medians, size=7)
  + labs(title="Testing stat_medians")
)
```

<!-- TODO: Revise -->
::: {.callout-note collapse="false"}
# You may have noticed ...

**... that we don't use `"medians"` as the `stat` argument. But you could!**  If you prefer, you could write `geom_point(stat="medians", size = 7)` which will direct to your new `stat_medians` under the hood.
:::

### Test Stat group-wise behavior

Test group-wise behavior by using a discrete variable with an group-triggering aesthetic like color, fill, or group, or by faceting.



```{python}
last_plot() + aes(color="species")
```

:::  {.callout-tip collapse="true"}
# Pro tip: Think about an early exit (don't define a user-facing function) ...

You might be thinking, what we've done would already be pretty useful to me.  Can I just use my Stat as-is within `geom_*()` functions?  

The short answer is 'yes'!  If you just want to use the Stat yourself locally in a script, there might not be much reason to go on to Step 3, user-facing functions.  But if you have a wider audience in mind, i.e. internal to organization or open sourcing in a package, probably a more succinct expression of what functionality you deliver will be useful - i.e. write the user-facing functions.
:::


:::   {.callout-tip collapse="true"}
# Pro tip: consider using `layer()` function to test instead of `geom_*(stat = StatNew)`

Instead of using a `geom_*()` function, you might prefer to use the `layer()` function in your testing step.  Occasionally, you *must* to go this route; for example, `geom_vline()` contain no `stat` argument, but you can use the GeomVline in `layer()`.  If you are teaching this content, using `layer()` may help you better connect this step with the next, defining the user-facing functions.  

A test of StatMedians using this method follows.  You can see it is a little more verbose, as there is no default for the position argument, and setting the size must be handled with a little more care.


```{python}
(
    ggplot(penguins)
    + aes(x="bill_depth_mm", y="bill_length_mm")
    + geom_point()
    + layer(
        geom=geom_point,
        stat=stat_medians,
        position="identity",
        size=7,
    )
    + labs(title = "Testing stat_medians with layer() function")
)
```

:::


## Step 3: Define user-facing functions. Test.

<!-- Step removed -->

### Define geom_*() class

> 'Most plotnine users are accustomed to adding geoms, not stats, when building up a plot.' *ggplot2: Elegant Graphics for Data Analysis*.

Because plotnine users may be more accustomed to using layers that have the `geom_` prefix, you might also define a `geom_` function with almost the same properties as the `stat_`.  Here we'll use `make_constructor()` for convenience.

```{python}
class geom_medians(geom_point):
    DEFAULT_PARAMS = {"stat": "medians"}
```


### Test/Enjoy your `geom_medians()` function!

### Test geom_medians()

```{python}
## Test user-facing.

(
    ggplot(penguins)
    + aes(x="bill_depth_mm", y="bill_length_mm")
    + geom_point()
    + geom_medians(size=8)
    + labs(title="Testing geom_medians()")
)
```

### Test group-wise behavior

```{python}
last_plot() + aes(color="species")
```

### Test stat_*() function with another Geom.

```{python}
(
    last_plot()
    + stat_medians(geom="label", mapping=aes(label="species"))
    + labs(subtitle="and stat_medians()")
)
```


# Done! Time for a review.

Here is a quick review of the functions and ggproto objects we've covered, dropping tests and discussion.

::: {.callout-note collapse="false"}
# Review
```{python}
# Step 1. Define compute
def compute_group_medians(data, scales=None):
    return data[['x', 'y']].median().to_frame().T


# Step 2. Define Stat
class stat_medians(stat):
    REQUIRED_AES = {"x", "y"}
    DEFAULT_PARAMS = {"geom": "point"}

    def compute_group(self, data, scales):
        return compute_group_medians(data)

# Step 3. Define Geom
class geom_medians(geom_point):
    DEFAULT_PARAMS = {"stat": "medians"}
```


:::


# Your Turn: write `geom_means()`

Using the `geom_medians` Recipe #1 as a reference, try to create a `geom_means()` function that draws a point at the means of x and y. You may also write convenience geom_*() functions. 

### Step 00: load libraries, data
```{pyodide}
#| setup: true
#| exercise: geom_means
#| warning: false

from plotnine import *
from plotnine.data import penguins

penguins.head()
```

### Step 0: Use base plotnine to get the job done

```{pyodide}
#| exercise: geom_means
# Step 0: Use base plotnine to get the job done

(
    penguins[["bill_length_mm", "___"]]
    .___()
    .to_frame()
    .T
    .add_prefix("mean_")
)


(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point()
  + geom_point(
      data=penguins_medians,
      aes(x="mean_bill_depth_mm", y="___")
      size=8,
      color="red",
   )
)
```

### Step 1: Write compute function. Test.

```{pyodide}
#| exercise: geom_means
# Define.

def compute_group_means(data, scales=None):
    return data[["x", "y"]].mean().to_frame().T

# Test.
(
    penguins
    .eval("x = bill_depth_mm")
    .eval("___ = bill_length_mm")
    [["x", "y"]]
    .pipe(compute_group_means)
)
```

### Step 2: Write Stat.

```{pyodide}
#| exercise: geom_means
# Define.
class stat_means(stat):
    REQUIRED_AES = {"x", "y"}
    DEFAULT_PARAMS = {"geom": "point"}

    def compute_group(self, data, scales):
        return ___(data)


# Test.
(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point()
  + geom_point(stat=___, size=8, color="red")
)
```



### Step 3: Write Geom.

```{pyodide}
# Define geom_means
class geom_medians(geom_point):
    DEFAULT_PARAMS = {"stat": "___"}

# Test.
(
  ggplot(penguins)
  + aes(x="bill_depth_mm", y="bill_length_mm")
  + geom_point() +
  + ____(size = 8, color = "red")
)
```




# Next up: Recipe 2 `geom_id()`

How would you write the function which annotates coordinates (x,y) for data points on a scatterplot? Go to [Recipe 2](./recipe2coordinates.qmd).





::: {.callout-note collapse="true"}
### Pro tip: check out `stat_manual()` for one-off, group-wise compute in the next ggplot2 release or [`statexpress.qstat()`](https://github.com/EvaMaeRey/statexpress) for a quick stat short-cut in extension explorations.

```{python}
from statexpress import qstat, qstat_panel, qstat_layer
```

Examples follow:

```{python}
#| eval: false

def mean_fun(data, scales):
   return data[["x", "y"]].mean().to_frame().T

(
   ggplot(penguins)
   + aes(x="bill_length_mm", y="bill_length_mm")
   + geom_point()
   + geom_point(stat=qstat(mean_fun))
)
```


```{python}
#| eval: false
## Consider statexpress.qstat_*() functions for more
## flexibility and exploratory extension work
def mean_fun(data, scales):
   return data[["x", "y"]].mean().to_frame().T

(
   ggplot(penguins)
   + aes(x="bill_length_mm", y="bill_length_mm")
   + geom_point()
   + geom_point(stat=qstat(mean_fun), size=8)
)


#--------------------------------------------------

## option 2, use geom_point(stat = "manual")

def means_fun2(data):
   return data[["x", "y"]].mean().to_frame().T

# TODO: uncomment stat_manual() example when it's available in plotnine
### usage A (geom )
(
   ggplot(penguins)
   + aes(x="bill_length_mm", y="bill_length_mm")
   + geom_point()
#    + geom_point(stat="manual", fun=means_fun2, size=8)
)


### usage B (geom)

(
    ggplot(penguins)
    + aes(x="bill_length_mm", y="bill_length_mm")
    # + stat_manual(
    #     size=8,  # geom default is "point"
    #     fun=means_fun2
    # )
)
```

:::
